global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gateway:8080"]

  - job_name: "flight-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["flight-service:8081"]

  - job_name: "crew-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["crew-service:8082"]

  - job_name: "delay-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["delay-service:8083"]

  - job_name: "kpi-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["kpi-service:8084"]

  - job_name: "streaming-analytics"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["streaming-analytics:8086"]

  - job_name: "ingestion-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["ingestion-service:8090"]

  - job_name: "flight-simulator"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["flight-simulator:8091"]
