server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      default-filters:
        - name: ApiKeyFilter
        - AddRequestHeader=X-Correlation-Id, #{T(java.util.UUID).randomUUID().toString()}

      routes:
        - id: flight-service
          uri: http://flight-service:8081
          predicates:
            - Path=/api/flights/**

        - id: crew-service
          uri: http://crew-service:8082
          predicates:
            - Path=/api/crew/**

        - id: delay-service
          uri: http://delay-service:8083
          predicates:
            - Path=/api/delays/**

        - id: kpi-service
          uri: http://kpi-service:8084
          predicates:
            - Path=/api/kpis/**

        - id: streaming-analytics
          uri: http://streaming-analytics:8086
          predicates:
            - Path=/api/analytics/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4318/v1/traces}
