apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: aerostream-staging
patches:
  - target:
      kind: Namespace
      name: aerostream
    patch: |-
      - op: replace
        path: /metadata/name
        value: aerostream-staging
  - target:
      kind: ConfigMap
      name: platform-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: staging
      - op: replace
        path: /data/CLUSTER_PROFILE
        value: aks-staging
  - target:
      kind: Ingress
      name: aerostream
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging.aerostream.local
